---
title: "shinyApp"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Load packages:
```{r}
library(shiny)
library(shinythemes)
library(bslib)
library(tidyverse)
library(plotly)
library(ggplot2)
library(rjson)
```

import CDC vaccination data:

```{r}

cdcData_unprocessed <- read_csv("data/covid19_vaccinations_in_the_united_states.csv", skip = 2) 
cdcData_unprocessed <- cdcData_unprocessed %>% rename_with(~ gsub(" ", "_", names(cdcData_unprocessed)))
cdcData_unprocessed <- cdcData_unprocessed %>% rename_with(~ gsub("/", "_", names(cdcData_unprocessed)))
cdcData_unprocessed <- cdcData_unprocessed %>% mutate(State_Territory_Federal_Entity = gsub(" State", "", State_Territory_Federal_Entity))

#I need to merge the hexgrid info with the info above:

stateInfo <- read_csv("data/us_states_hexgrid.csv") %>% 
  select(-the_geom, -cartodb_id, -created_at, -updated_at, -bees) %>%
  mutate(google_name = gsub(" \\(United States\\)", "", google_name))

demoData <- read_csv("data/healthCareExpendituresperCapita.csv")
demoDataJoined <- left_join(stateInfo, demoData, by = c("google_name" = "Location"))

cdcData <- left_join(stateInfo, cdcData_unprocessed, by = c("google_name" = "State_Territory_Federal_Entity"))



#I think I need to split the data into two data frames: one where company is a variable, and one where it is not:

cdcData_agnostic <- cdcData %>% 
  select(contains("label", ignore.case = TRUE) |
           contains("iso", ignore.case = TRUE) |
           contains("google", ignore.case = TRUE) |
           contains("100k", ignore.case=TRUE)) %>%
  na_if("N/A") %>% 
  drop_na()

colnames(cdcData_agnostic) <- c("Shortened", "ISOname", "Name",
                               "Total_DeliveredPer100K", 
                               "18plus_DeliveredPer100K", 
                               "Total_AdministeredPer100K", 
                               "18plus_AdministeredPer100K", 
                               "65plus_AdministeredPer100K",
                               "65plus_DeliveredPer100K")

cdcData_agnostic <- cdcData_agnostic %>%
  mutate_at(vars("Shortened", "ISOname", "Name",
                               "Total_DeliveredPer100K", 
                               "18plus_DeliveredPer100K", 
                               "Total_AdministeredPer100K", 
                               "18plus_AdministeredPer100K", 
                               "65plus_AdministeredPer100K",
                               "65plus_DeliveredPer100K"), 
            list(factor))

cdcData_agnosticLong <- cdcData_agnostic %>%
  pivot_longer(
    !c(Shortened, ISOname, Name),
    names_to= c("Group", ".value"),
    names_sep="_")

cdcData_company <- cdcData %>% select(contains("label", ignore.case = TRUE) |
                                        contains("iso", ignore.case = TRUE) |
                                        contains("google", ignore.case = TRUE) |
                                        contains("moderna", ignore.case=TRUE) | 
                                         contains("pfizer", ignore.case=TRUE) | 
                                         contains("janssen", ignore.case=TRUE))

colnames(cdcData_company) <- c("Shortened", "ISOname", "Name",
                               "TotalDelivered_Moderna", 
                               "TotalAdministered_Moderna", 
                               "PeopleFullyVaccinated_Moderna", 
                               "18plusFullyVaccinated_Moderna", 
                               "65plusFullyVaccinated_Moderna",
                               "TotalDelivered_Pfizer", 
                               "TotalAdministered_Pfizer", 
                               "PeopleFullyVaccinated_Pfizer", 
                               "18plusFullyVaccinated_Pfizer", 
                               "65plusFullyVaccinated_Pfizer",
                               "TotalDelivered_Janssen", 
                               "TotalAdministered_Janssen", 
                               "PeopleFullyVaccinated_Janssen", 
                               "18plusFullyVaccinated_Janssen", 
                               "65plusFullyVaccinated_Janssen")


cdcDataLong <- cdcData_company %>%
  pivot_longer(
    !c(Shortened, ISOname, Name),
    names_to= c(".value", "manufacturer"),
    names_sep="_")

write_rds(cdcData_agnosticLong, "data/cdcData_agnosticLong.rds")

```

I'm curious to see how much of a pain it would be to incorporate the time data:

```{r}

agnosticTimeLine <- read_csv("data/706_Temporal_Data.csv", skip=5)[,c(1,2,5,6)]
agnosticTimeLine <- agnosticTimeLine %>% filter(!str_detect(`Age Group`, "unknown"))
agnosticTimeLine <- agnosticTimeLine %>% filter(!str_detect(`Age Group`, "Ages_<18yrs"))
agnosticTimeLine <- agnosticTimeLine %>% filter(!str_detect(`Age Group`, "Age_known"))

agnosticTimeLine$Date <- lubridate::mdy(agnosticTimeLine$Date)

agnosticTimeLine$betterAgeGroup <- ifelse(agnosticTimeLine$`Age Group` == "Ages_75+_yrs" | agnosticTimeLine$`Age Group` == "Ages_65-74_yrs",
"65plus", "18plus") 
agnosticTimeLine <- agnosticTimeLine[,-2]


agnosticTimeLineGroupedOneDose <- group_by(agnosticTimeLine, Date, betterAgeGroup) %>% summarise(`Percent of age group with at least one dose` = mean(`Percent of age group with at least one dose`))
agnosticTimeLineGroupedFully <- group_by(agnosticTimeLine, Date, betterAgeGroup) %>% summarise(`Percent of age group fully vaccinated` = mean(`Percent of age group fully vaccinated`))
agnosticTimeLineGroupedAll <- left_join(agnosticTimeLineGroupedOneDose, agnosticTimeLineGroupedFully)

agnosticTimeLineGroupedOneDose_Total <- group_by(agnosticTimeLineGroupedOneDose, Date) %>% summarise(`Percent of age group with at least one dose` = mean(`Percent of age group with at least one dose`))
agnosticTimeLineGroupedFully_Total <- group_by(agnosticTimeLineGroupedFully, Date) %>% summarise(`Percent of age group fully vaccinated` = mean(`Percent of age group fully vaccinated`))
agnosticTimeLineGroupedAll_Total <- left_join(agnosticTimeLineGroupedOneDose_Total, agnosticTimeLineGroupedFully_Total)

write_rds(agnosticTimeLineGroupedAll, "data/agnosticTimeLineGroupedAll.rds")
write_rds(agnosticTimeLineGroupedAll_Total, "data/agnosticTimeLineGroupedAll_Total.rds")

```

I've done a bunch of work on the manufacturer-independent side, but now I want to work on the side that does analysis by manufacturer:

```{r}

pfizerTimelineDownload <- download.file("https://data.cdc.gov/resource/saz5-9hgg.csv", "data/updatedPfizer.csv")
modernaTimelineDownload <- download.file("https://data.cdc.gov/resource/b7pe-5nws.csv", "data/updatedModerna.csv")
johnsonTimelineDownload <- download.file("https://data.cdc.gov/resource/w9zu-fywh.csv", "data/updatedJohnson.csv")

pfizerTimeline <- read_csv("data/updatedPfizer.csv")
modernaTimeline <- read_csv("data/updatedModerna.csv")
johnsonTimeline <- read_csv("data/updatedJohnson.csv")

colnames(pfizerTimeline) <- c("State", "Week", "FirstDoseAllocation", "SecondDoseAllocation")
colnames(modernaTimeline) <- c("State", "Week", "FirstDoseAllocation", "SecondDoseAllocation")
colnames(johnsonTimeline) <- c("State", "Week", "TotalDoseAllocation")

pfizerTimeline <- pfizerTimeline %>% mutate(TotalDoseAllocation = FirstDoseAllocation + SecondDoseAllocation)
modernaTimeline <- modernaTimeline %>% mutate(TotalDoseAllocation = FirstDoseAllocation + SecondDoseAllocation)

pfizerTimeline$Week <- lubridate::ymd(pfizerTimeline$Week)
modernaTimeline$Week <- lubridate::ymd(modernaTimeline$Week)
johnsonTimeline$Week <- lubridate::ymd(johnsonTimeline$Week)

pfizerTimeline <- pfizerTimeline %>% group_by(State)
modernaTimeline <- modernaTimeline %>% group_by(State)
johnsonTimeline <- johnsonTimeline %>% group_by(State)

pfizerTimeline <- left_join(demoDataJoined, pfizerTimeline, by = c("google_name" = "State"))
modernaTimeline <- left_join(demoDataJoined, modernaTimeline, by = c("google_name" = "State"))
johnsonTimeline <- left_join(demoDataJoined, johnsonTimeline, by = c("google_name" = "State"))

pfizerTimeline <- pfizerTimeline %>% mutate(TotalDoseAllocationPer100k = TotalDoseAllocation/(PopulationEstimate/100000))
modernaTimeline <- modernaTimeline %>% mutate(TotalDoseAllocationPer100k = TotalDoseAllocation/(PopulationEstimate/100000))
johnsonTimeline <- johnsonTimeline %>% mutate(TotalDoseAllocationPer100k = TotalDoseAllocation/(PopulationEstimate/100000))

write_rds(pfizerTimeline, "data/pfizerTimeline.rds")
write_rds(modernaTimeline, "data/modernaTimeline")
write_rds(johnsonTimeline, "data/johnsonTimeline")


#plot_ly(modernaTimeline, x=~Week, y=~FirstDoseAllocation, mode = 'lines+markers')
```

